version: '3.8'

services:
  backend:
    build: 
      context: ../
      dockerfile: deploy/Dockerfile.backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../session_audit.json:/app/session_audit.json
  
  bot:
    build:
      context: ../
      dockerfile: deploy/Dockerfile.bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../session_audit.json:/app/session_audit.json
